spring.application.name=security

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

app.jwt.secret=${JWT_SECRET}
# Access token: 15 minutos
app.jwt.expiration-ms=900000
# Refresh token: 7 días
app.jwt.refresh-expiration-ms=604800000
