spring.application.name=database_connection

spring.datasource.url=jdbc:postgresql://localhost:5432/ejemplo_136
spring.datasource.username=ejemplo_136
spring.datasource.password=ejemplo_136

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true