FROM node:24.14-alpine AS builder

WORKDIR /app

COPY ./package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist/front/browser /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
