services:
    postgres:
        image: postgres:18-alpine
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=test
        ports:
            - "5400:5432"
        volumes:
            - compose_data_136:/var/lib/postgresql/18/docker

volumes:
    compose_data_136:
